[package]
name = "pfosix_rust_core"
version = "0.1.0"
edition = "2021"
description = "The core LifeAxiom logic for the PFOSIX Uzerverse."
repository = "https://github.com/pfos/ncombo"
license = "MIT OR Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
once_cell = "1.18"
